"""empty message

Revision ID: 2e566b096f89
Revises: ed82c321bb89
Create Date: 2023-04-17 23:08:46.586308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e566b096f89'
down_revision = 'ed82c321bb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prize', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prize', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
