"""empty message

Revision ID: 734a31f89176
Revises: 2e566b096f89
Create Date: 2023-04-17 23:40:25.704068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734a31f89176'
down_revision = '2e566b096f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rewards_initial', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('rewards_initial')

    # ### end Alembic commands ###
