"""empty message

Revision ID: ba9378c84b1b
Revises: 734a31f89176
Create Date: 2023-04-18 11:00:46.962368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9378c84b1b'
down_revision = '734a31f89176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newquest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip', sa.String(), nullable=True))

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('tip')

    with op.batch_alter_table('newquest', schema=None) as batch_op:
        batch_op.drop_column('tip')

    # ### end Alembic commands ###
